### ISSUE TITLE
Error due to timezone

### ISSUE THREAD

**Issue by stschiff** [nevrome/covid19germany#21]
```
dat <- covid19germany::get_RKI_timeseries(cache=F) %>% covid19germany::group_RKI_timeseries()
```
yields
```
Warning message:
In as.POSIXlt.POSIXct(x, tz = tz) : unknown timezone 'CEST'
```

**Comment by nevrome** [comment]
OK - I did some googling and found out that this timezone stuff will eventually drive you crazy. So I just turned it off. Please try the latest version. It was a nice idea.

**Comment by stschiff** [comment]
Sounds totally OK. This is all day-based anyway, isn't it? Feel free to close this.

**Comment by nevrome** [comment]
Imagine how complicated this time zone business will be, if/when we life on multiple planets!
