### ISSUE TITLE
Einige Landkreise fehlen seit 4/4/2020

### ISSUE THREAD

**Issue by Sandv** [nevrome/covid19germany#22]
Seit gestern fehlen viele Landkreise, unter anderem alle in Bayern. Ich vermute das liegt an den RKI Ursprungsdaten, kann das aber nicht verifizieren...
Vielen Dank fuer die tolle Package!
Veit

**Comment by nevrome** [comment]
Ok - wenn ich das richtig sehe, dann fehlen die Daten in der Zeitreihe, nicht aber im spatial Datensatz. Sehr ärgerlich. Ich hoffe, dass sich das von alleine korrigiert. Wenn das wiederholt vorkommt, müssen wir die Daten irgendwo anders hinschaufeln und cachen.

![Rplot01](https://user-images.githubusercontent.com/10789038/78508644-ae322180-7788-11ea-8eaa-d2633ebfd349.jpeg)

**Comment by Sandv** [comment]
Ja, es funktioniert bei mir auch wieder!
Vielen Dank
Veit
