### ISSUE TITLE
provide raw data only

### ISSUE THREAD

**Issue by psteinb** [nevrome/covid19germany#26]
Looking at 
https://github.com/nevrome/covid19germany/blob/b3401126a7b19b74c84063e9002e35ce3549a231/R/get_RKI_timeseries.R#L81
and in the spirit of openness, I would love to have an option in `get_RKI_timeseries` to download the __raw__ RKI data. Would it be ok for me to send a PR?

**Comment by nevrome** [comment]
Sure - go ahead.

**Comment by psteinb** [comment]
So that I could say:
```r
df = covid19germany::get_RKI_timeseries(cache=F, raw=T)
```
and I'd get the plain csv from the arcgis website. I think this would be very helpful.

**Comment by nevrome** [comment]
merged #27 :+1:
