### ISSUE TITLE
shiny app fails - FID not present in data

### ISSUE THREAD

**Issue by arne1921KF** [nevrome/covid19germany#29]
`Error message: Column `FID` not found in `.data``

I guess RKI/ESRI updated their feature tables and broke the code?

**Comment by nevrome** [comment]
Ah right - thanks for the information. I fixed that already some time ago in the package, but forgot to update the shiny app. Please try now!

**Comment by nevrome** [comment]
Ah - wait. I deployed to the wrong path. One moment.

**Comment by nevrome** [comment]
Now.

**Comment by arne1921KF** [comment]
Fixed. Thanks. 
Also thanks for the package. I'm currently thinking about setting up a twitter bot to tweet out some Landkreis numbers, as a service. Your packages makes it pretty straightforward to filter that data.
