### ISSUE TITLE
get_RKI_timeseries(): Date is NA!

### ISSUE THREAD

**Issue by wulms** [nevrome/covid19germany#35]
Hi guys,

I wanted to load the RKI Covid data, but all Dates are NA, when using get_RKI_timeseries()

Edit: Okay - today the dates are back. Only in StartOfdiseaseDate some NAs - is that right?

Awesome work!

Best,
Niklas

**Comment by nevrome** [comment]
> Edit: Okay - today the dates are back. Only in StartOfdiseaseDate some NAs - is that right?

I think that is correct.

**Comment by wulms** [comment]
Thank you for your fast reply! 

Stay healthy :)

**Comment by nevrome** [comment]
Let me know if you observe any issues with the date parsing and if our simplified data product is not consistent with the raw table the RKI provides. Sometimes the reason for this is a bad upload by the RKI, though, so many issues get resolved automatically within 24 hours.
