### ISSUE TITLE
Autoren

### ISSUE THREAD

**Issue by nevrome** [nevrome/covid19germany#5]
Alle Autoren sollten im DESCRIPTION file eingetragen sein. Bitte nehmt diese Operation selbst vor.

https://github.com/nevrome/covid19germany/blob/master/DESCRIPTION vgl.
https://github.com/ropensci/c14bazAAR/blob/master/DESCRIPTION

@mlange-42 @moritzaschoff @stschiff

**Comment by stschiff** [comment]
Done.
